export interface IndexMeta { name: string; category: string; }

export const ALL_NSE_INDICES: IndexMeta[] = [
  // Broad Market
  { name: "NIFTY 50",             category: "Broad Market" },
  { name: "NIFTY NEXT 50",        category: "Broad Market" },
  { name: "NIFTY 100",            category: "Broad Market" },
  { name: "NIFTY 200",            category: "Broad Market" },
  { name: "NIFTY 500",            category: "Broad Market" },
  { name: "NIFTY TOTAL MARKET",   category: "Broad Market" },
  // Market Cap
  { name: "NIFTY MIDCAP 50",            category: "Market Cap" },
  { name: "NIFTY MIDCAP 100",           category: "Market Cap" },
  { name: "NIFTY MIDCAP 150",           category: "Market Cap" },
  { name: "NIFTY MIDCAP SELECT",        category: "Market Cap" },
  { name: "NIFTY SMALLCAP 50",          category: "Market Cap" },
  { name: "NIFTY SMALLCAP 100",         category: "Market Cap" },
  { name: "NIFTY SMALLCAP 250",         category: "Market Cap" },
  { name: "NIFTY MIDSMALLCAP 400",      category: "Market Cap" },
  { name: "NIFTY MICROCAP 250",         category: "Market Cap" },
  { name: "NIFTY LARGEMIDCAP 250",      category: "Market Cap" },
  { name: "NIFTY500 MULTICAP 50:25:25", category: "Market Cap" },
  { name: "NIFTY500 LARGEMIDSMALL EQUAL-CAP WEIGHTED", category: "Market Cap" },
  // Sectoral
  { name: "NIFTY AUTO",               category: "Sectoral" },
  { name: "NIFTY BANK",               category: "Sectoral" },
  { name: "NIFTY ENERGY",             category: "Sectoral" },
  { name: "NIFTY FINANCIAL SERVICES", category: "Sectoral" },
  { name: "NIFTY FINANCIAL SERVICES 25/50", category: "Sectoral" },
  { name: "NIFTY FMCG",               category: "Sectoral" },
  { name: "NIFTY IT",                 category: "Sectoral" },
  { name: "NIFTY MEDIA",              category: "Sectoral" },
  { name: "NIFTY METAL",              category: "Sectoral" },
  { name: "NIFTY PHARMA",             category: "Sectoral" },
  { name: "NIFTY PSU BANK",           category: "Sectoral" },
  { name: "NIFTY REALTY",             category: "Sectoral" },
  { name: "NIFTY PRIVATE BANK",       category: "Sectoral" },
  { name: "NIFTY HEALTHCARE INDEX",   category: "Sectoral" },
  { name: "NIFTY CONSUMER DURABLES",  category: "Sectoral" },
  { name: "NIFTY OIL & GAS",          category: "Sectoral" },
  { name: "NIFTY CHEMICALS",          category: "Sectoral" },
  { name: "NIFTY COMMODITIES",        category: "Sectoral" },
  { name: "NIFTY INFRASTRUCTURE",     category: "Sectoral" },
  { name: "NIFTY SERVICES SECTOR",    category: "Sectoral" },
  { name: "NIFTY MNC",                category: "Sectoral" },
  { name: "NIFTY PSE",                category: "Sectoral" },
  { name: "NIFTY CPSE",               category: "Sectoral" },
  // Thematic
  { name: "NIFTY INDIA CONSUMPTION",   category: "Thematic" },
  { name: "NIFTY INDIA DIGITAL",       category: "Thematic" },
  { name: "NIFTY INDIA MANUFACTURING", category: "Thematic" },
  { name: "NIFTY INDIA DEFENCE",       category: "Thematic" },
  { name: "NIFTY INDIA TOURISM",       category: "Thematic" },
  { name: "NIFTY CAPITAL MARKETS",     category: "Thematic" },
  { name: "NIFTY EV & NEW AGE AUTOMOTIVE", category: "Thematic" },
  { name: "NIFTY INDIA NEW AGE CONSUMPTION", category: "Thematic" },
  { name: "NIFTY MOBILITY",            category: "Thematic" },
  { name: "NIFTY CORE HOUSING",        category: "Thematic" },
  { name: "NIFTY HOUSING",             category: "Thematic" },
  { name: "NIFTY IPO",                 category: "Thematic" },
  { name: "NIFTY RURAL",               category: "Thematic" },
  { name: "NIFTY TRANSPORTATION & LOGISTICS", category: "Thematic" },
  { name: "NIFTY GROWTH SECTORS 15",   category: "Thematic" },
  { name: "NIFTY NON-CYCLICAL CONSUMER",category:"Thematic" },
  { name: "NIFTY100 ESG",              category: "Thematic" },
  { name: "NIFTY100 ENHANCED ESG",     category: "Thematic" },
  { name: "NIFTY INDIA FPI 150",       category: "Thematic" },
  { name: "NIFTY INDIA INFRASTRUCTURE & LOGISTICS", category: "Thematic" },
  { name: "NIFTY INDIA INTERNET",      category: "Thematic" },
  { name: "NIFTY INDIA RAILWAYS PSU",  category: "Thematic" },
  { name: "NIFTY WAVES",               category: "Thematic" },
  { name: "NIFTY CONGLOMERATE 50",     category: "Thematic" },
  { name: "NIFTY INDIA SELECT 5 CORPORATE GROUPS (MAATR)", category: "Thematic" },
  { name: "NIFTY INDIA CORPORATE GROUP INDEX - TATA GROUP 25% CAP", category: "Thematic" },
  { name: "NIFTY500 MULTICAP INDIA MANUFACTURING 50:30:20", category: "Thematic" },
  { name: "NIFTY500 MULTICAP INFRASTRUCTURE 50:30:20", category: "Thematic" },
  // Strategy
  { name: "NIFTY50 VALUE 20",          category: "Strategy" },
  { name: "NIFTY100 QUALITY 30",       category: "Strategy" },
  { name: "NIFTY50 EQUAL WEIGHT",      category: "Strategy" },
  { name: "NIFTY100 EQUAL WEIGHT",     category: "Strategy" },
  { name: "NIFTY100 LOW VOLATILITY 30",category: "Strategy" },
  { name: "NIFTY ALPHA 50",            category: "Strategy" },
  { name: "NIFTY200 QUALITY 30",       category: "Strategy" },
  { name: "NIFTY ALPHA LOW-VOLATILITY 30", category: "Strategy" },
  { name: "NIFTY200 MOMENTUM 30",      category: "Strategy" },
  { name: "NIFTY MIDCAP150 QUALITY 50",category: "Strategy" },
  { name: "NIFTY200 ALPHA 30",         category: "Strategy" },
  { name: "NIFTY MIDCAP150 MOMENTUM 50",category:"Strategy" },
  { name: "NIFTY500 MOMENTUM 50",      category: "Strategy" },
  { name: "NIFTY MIDSMALLCAP400 MOMENTUM QUALITY 100", category: "Strategy" },
  { name: "NIFTY SMALLCAP250 MOMENTUM QUALITY 100",    category: "Strategy" },
  { name: "NIFTY TOP 10 EQUAL WEIGHT", category: "Strategy" },
  { name: "NIFTY ALPHA QUALITY LOW-VOLATILITY 30",  category: "Strategy" },
  { name: "NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30", category: "Strategy" },
  { name: "NIFTY HIGH BETA 50",        category: "Strategy" },
  { name: "NIFTY LOW VOLATILITY 50",   category: "Strategy" },
  { name: "NIFTY QUALITY LOW-VOLATILITY 30",  category: "Strategy" },
  { name: "NIFTY SMALLCAP250 QUALITY 50",     category: "Strategy" },
  { name: "NIFTY TOP 15 EQUAL WEIGHT", category: "Strategy" },
  { name: "NIFTY100 ALPHA 30",         category: "Strategy" },
  { name: "NIFTY200 VALUE 30",         category: "Strategy" },
  { name: "NIFTY500 EQUAL WEIGHT",     category: "Strategy" },
  { name: "NIFTY500 MULTICAP MOMENTUM QUALITY 50", category: "Strategy" },
  { name: "NIFTY500 VALUE 50",         category: "Strategy" },
  { name: "NIFTY TOP 20 EQUAL WEIGHT", category: "Strategy" },
  { name: "NIFTY500 QUALITY 50",       category: "Strategy" },
  { name: "NIFTY500 LOW VOLATILITY 50",category: "Strategy" },
  { name: "NIFTY500 MULTIFACTOR MQVLV 50", category: "Strategy" },
  { name: "NIFTY DIVIDEND OPPORTUNITIES 50",   category: "Strategy" },
  { name: "NIFTY100 LIQUID 15",        category: "Strategy" },
  { name: "NIFTY MIDCAP LIQUID 15",    category: "Strategy" },
  { name: "NIFTY TOTAL MARKET MOMENTUM QUALITY 50", category: "Strategy" },
  { name: "NIFTY500 FLEXICAP QUALITY 30",  category: "Strategy" },
  { name: "NIFTY500 HEALTHCARE",       category: "Strategy" },
  // Mid/Small Sectoral
  { name: "NIFTY MIDSMALL HEALTHCARE",         category: "Mid/Small" },
  { name: "NIFTY FINANCIAL SERVICES EX-BANK",  category: "Mid/Small" },
  { name: "NIFTY MIDSMALL FINANCIAL SERVICES", category: "Mid/Small" },
  { name: "NIFTY MIDSMALL IT & TELECOM",       category: "Mid/Small" },
  { name: "NIFTY MIDSMALL INDIA CONSUMPTION",  category: "Mid/Small" },
  // Shariah
  { name: "NIFTY SHARIAH 25",  category: "Shariah" },
  { name: "NIFTY50 SHARIAH",   category: "Shariah" },
  { name: "NIFTY500 SHARIAH",  category: "Shariah" },
  { name: "INDIA VIX",         category: "Volatility" },
];

// Realistic base prices for well-known indices
export const INDEX_BASE_PRICES: Record<string, number> = {
  "NIFTY 50": 24350, "NIFTY NEXT 50": 68500, "NIFTY 100": 25100,
  "NIFTY 200": 13200, "NIFTY 500": 22000, "NIFTY TOTAL MARKET": 16800,
  "NIFTY BANK": 52800, "NIFTY IT": 41200, "NIFTY PHARMA": 22400,
  "NIFTY AUTO": 24800, "NIFTY FMCG": 58900, "NIFTY METAL": 9800,
  "NIFTY REALTY": 1050, "NIFTY ENERGY": 42500, "NIFTY MIDCAP 50": 16800,
  "NIFTY MIDCAP 100": 58900, "NIFTY SMALLCAP 100": 18900, "NIFTY MIDCAP SELECT": 12800,
  "NIFTY FINANCIAL SERVICES": 24800, "NIFTY PSU BANK": 6800,
  "NIFTY PRIVATE BANK": 25800, "NIFTY HEALTHCARE INDEX": 14200,
  "NIFTY CONSUMER DURABLES": 38900, "NIFTY OIL & GAS": 11800,
  "NIFTY INDIA DEFENCE": 8200, "NIFTY COMMODITIES": 8900,
  "NIFTY INFRASTRUCTURE": 9200, "NIFTY MEDIA": 2800, "NIFTY MNC": 31200,
  "NIFTY SMALLCAP 250": 15400, "NIFTY MIDCAP 150": 21800, "NIFTY LARGEMIDCAP 250": 14900,
  "NIFTY MIDSMALLCAP 400": 18200, "NIFTY MICROCAP 250": 19800,
  "NIFTY CPSE": 6400, "NIFTY PSE": 8900, "NIFTY SERVICES SECTOR": 28700,
};
