// Client-safe static symbols list — no server dependencies, no mock data
export interface SymbolInfo { symbol: string; name: string; sector: string; weight: number; }

export const NIFTY50_SYMBOLS: SymbolInfo[] = [
  { symbol:"RELIANCE",   name:"Reliance Industries",       sector:"Energy",         weight:10.5 },
  { symbol:"TCS",        name:"Tata Consultancy Services",  sector:"IT",             weight:8.2  },
  { symbol:"HDFCBANK",   name:"HDFC Bank",                  sector:"Banking",        weight:7.9  },
  { symbol:"ICICIBANK",  name:"ICICI Bank",                 sector:"Banking",        weight:6.8  },
  { symbol:"INFY",       name:"Infosys",                    sector:"IT",             weight:5.9  },
  { symbol:"HINDUNILVR", name:"Hindustan Unilever",         sector:"FMCG",           weight:4.1  },
  { symbol:"ITC",        name:"ITC Limited",                sector:"FMCG",           weight:3.8  },
  { symbol:"BHARTIARTL", name:"Bharti Airtel",              sector:"Telecom",        weight:3.5  },
  { symbol:"SBIN",       name:"State Bank of India",        sector:"Banking",        weight:3.2  },
  { symbol:"KOTAKBANK",  name:"Kotak Mahindra Bank",        sector:"Banking",        weight:3.1  },
  { symbol:"BAJFINANCE", name:"Bajaj Finance",              sector:"Finance",        weight:2.9  },
  { symbol:"LT",         name:"Larsen & Toubro",            sector:"Infrastructure", weight:2.7  },
  { symbol:"HCLTECH",    name:"HCL Technologies",           sector:"IT",             weight:2.4  },
  { symbol:"AXISBANK",   name:"Axis Bank",                  sector:"Banking",        weight:2.3  },
  { symbol:"ASIANPAINT", name:"Asian Paints",               sector:"Paints",         weight:2.1  },
  { symbol:"MARUTI",     name:"Maruti Suzuki",              sector:"Auto",           weight:2.0  },
  { symbol:"SUNPHARMA",  name:"Sun Pharmaceutical",         sector:"Pharma",         weight:1.9  },
  { symbol:"TITAN",      name:"Titan Company",              sector:"Consumer",       weight:1.8  },
  { symbol:"ULTRACEMCO", name:"UltraTech Cement",           sector:"Cement",         weight:1.7  },
  { symbol:"WIPRO",      name:"Wipro",                      sector:"IT",             weight:1.6  },
  { symbol:"NTPC",       name:"NTPC Limited",               sector:"Power",          weight:1.5  },
  { symbol:"POWERGRID",  name:"Power Grid Corp",            sector:"Power",          weight:1.4  },
  { symbol:"BAJAJFINSV", name:"Bajaj Finserv",              sector:"Finance",        weight:1.3  },
  { symbol:"NESTLEIND",  name:"Nestle India",               sector:"FMCG",           weight:1.2  },
  { symbol:"TECHM",      name:"Tech Mahindra",              sector:"IT",             weight:1.2  },
  { symbol:"M&M",        name:"Mahindra & Mahindra",        sector:"Auto",           weight:1.1  },
  { symbol:"ADANIPORTS", name:"Adani Ports",                sector:"Infrastructure", weight:1.0  },
  { symbol:"ONGC",       name:"Oil & Natural Gas Corp",     sector:"Energy",         weight:1.0  },
  { symbol:"JSWSTEEL",   name:"JSW Steel",                  sector:"Metals",         weight:0.9  },
  { symbol:"TATASTEEL",  name:"Tata Steel",                 sector:"Metals",         weight:0.9  },
  { symbol:"COALINDIA",  name:"Coal India",                 sector:"Mining",         weight:0.8  },
  { symbol:"DRREDDY",    name:"Dr. Reddy's Labs",           sector:"Pharma",         weight:0.7  },
  { symbol:"CIPLA",      name:"Cipla",                      sector:"Pharma",         weight:0.7  },
  { symbol:"EICHERMOT",  name:"Eicher Motors",              sector:"Auto",           weight:0.6  },
  { symbol:"BAJAJ-AUTO", name:"Bajaj Auto",                 sector:"Auto",           weight:0.6  },
  { symbol:"APOLLOHOSP", name:"Apollo Hospitals",           sector:"Healthcare",     weight:0.5  },
  { symbol:"TATACONSUM", name:"Tata Consumer Products",     sector:"FMCG",           weight:0.5  },
  { symbol:"GRASIM",     name:"Grasim Industries",          sector:"Diversified",    weight:0.5  },
  { symbol:"HINDALCO",   name:"Hindalco Industries",        sector:"Metals",         weight:0.5  },
  { symbol:"SBILIFE",    name:"SBI Life Insurance",         sector:"Insurance",      weight:0.4  },
  { symbol:"HDFCLIFE",   name:"HDFC Life Insurance",        sector:"Insurance",      weight:0.4  },
  { symbol:"ADANIENT",   name:"Adani Enterprises",          sector:"Diversified",    weight:0.4  },
  { symbol:"SHRIRAMFIN", name:"Shriram Finance",            sector:"Finance",        weight:0.3  },
  { symbol:"ETERNAL",    name:"Eternal",                    sector:"Consumer",       weight:0.1  },
  { symbol:"BEL",        name:"Bharat Electronics",         sector:"Defense",        weight:0.5  },
  { symbol:"JIOFIN",     name:"Jio Financial",              sector:"Finance",        weight:0.8  },
  { symbol:"TMPV",       name:"Tata Motors PV",             sector:"Auto",           weight:0.2  },
  { symbol:"INDIGO",     name:"InterGlobe Aviation",         sector:"Aviation",       weight:0.6  },
  { symbol:"TRENT",      name:"Trent Limited",              sector:"Retail",         weight:0.7  },
  { symbol:"MAXHEALTH",  name:"Max Healthcare",             sector:"Healthcare",     weight:0.5  },
];

// Lookup map for O(1) access
export const SYMBOL_MAP: Record<string, SymbolInfo> = Object.fromEntries(
  NIFTY50_SYMBOLS.map(s => [s.symbol, s])
);
